### ISSUE TITLE
installing from homebrew on catalina 10.15.7

### ISSUE THREAD

**Issue by julientaq** [FelixKratz/homebrew-formulae#1]
Hi there
installing on Catalina doesnt work through homebrew.
Here is the error i get.

Any idea on how to proceed?

```
➜  brew install sketchybar

==> Downloading https://github.com/FelixKratz/SketchyBar/archive/refs/tags/v2.3.3.tar.gz
Already downloaded: /Users/julientaq/Library/Caches/Homebrew/downloads/cbb4d4ccd944d6628ebd635d6a906d18029dda62095ed00b55ebdb6f36e8f2aa--SketchyBar-2.3.3.tar.gz

==> Installing sketchybar from felixkratz/formulae

==> cmake .
Last 15 lines from /Users/julientaq/Library/Logs/Homebrew/sketchybar/01.cmake:
    make[1]: *** [cmTC_8a04a] Error 1
    make: *** [cmTC_8a04a/fast] Error 2
    
      
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
See also "/tmp/sketchybar-20211231-36093-znxmsj/SketchyBar-2.3.3/CMakeFiles/CMakeOutput.log".
See also "/tmp/sketchybar-20211231-36093-znxmsj/SketchyBar-2.3.3/CMakeFiles/CMakeError.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/felixkratz/homebrew-formulae/issues

```

**Comment by FelixKratz** [comment]
Can you share these?

See also "/tmp/sketchybar-20211231-36093-znxmsj/SketchyBar-2.3.3/CMakeFiles/CMakeOutput.log".
See also "/tmp/sketchybar-20211231-36093-znxmsj/SketchyBar-2.3.3/CMakeFiles/CMakeError.log".

**Comment by julientaq** [comment]
Those files don’t exist on my computer 😱 

I guess homebrew move’em somewhere i can’t find. I’m digging.

**Comment by FelixKratz** [comment]
The cmake problem is likely also connected to the unsupported arm64 architecture that is set in `CMakeLists.txt`:
```cmake
set(CMAKE_OSX_ARCHITECTURES x86_64 arm64 CACHE STRING "")
```

**Comment by julientaq** [comment]
testing right away!
thanks!

**Comment by julientaq** [comment]
When you say source zip file are you talking of one specific file?

Also, how does brew know that it needs to fetch from localhost? Every time i try, it gets the formula on github

Thanks a lot for having taken the time to answer :)

**Comment by liangch** [comment]
The sketchybar.rb file is at<code>/usr/local/Homebrew/Library/Taps/felixkratz/homebrew-formulae</code>.

```
class Sketchybar < Formula
  env :std
  desc "Custom macOS statusbar with shell plugin, interaction and graph support"
  homepage "https://github.com/FelixKratz/SketchyBar"
  url "http://localhost:8181/2.4.3.zip"
  #sha256 "054ceb93746b74ad21e2b44d5fce64095125baf75679ae50ac70ca050998e9cd"
```

You will find the diff against my changes above (url and sha256 lines).  Better to backup the file and revert later before brew update.

Another way is you can make install from source files directly without brew.

**Comment by sadrach-cl** [comment]
> When you say source zip file are you talking of one specific file?
> 
> Also, how does brew know that it needs to fetch from localhost? Every time i try, it gets the formula on github
> 
> Thanks a lot for having taken the time to answer :)

https://github.com/sadrach-cl/conf/tree/main/SketchyBar

**Comment by Edwardtw92** [comment]
Hello, I am having the same issue on macOS Catalina, did anyone manage to resolve the issue?

**Comment by FelixKratz** [comment]
I believe you can clone the repository and run „make x86“ inside to build the binary for catalina. It is not working from brew because it tries to build a universal binary for arm64 and x86 and catalina cant do that sadly. As it seems that many people still use catalina I might invest some time to fix the formula but I have no way to test as my machines all run >= big sur. Does anyone know how I would check for operating system version in the brew formula?

**Comment by FelixKratz** [comment]
I have tried to implement it in the brew formula, could someone try it and let me know if it works?

**Comment by julientaq** [comment]
Up and running!

Thanks a lot @FelixKratz
