### ISSUE TITLE
Warning: Calling plist_options is deprecated! Use service.require_root instead.

### ISSUE THREAD

**Issue by cobcobs** [FelixKratz/homebrew-formulae#2]
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the felixkratz/formulae tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/felixkratz/homebrew-formulae/sketchybar.rb:47

**Comment by FelixKratz** [comment]
should be fixed
